### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by havudk1707** [ain/smartbanner.js#10]
Sorry.
But I think your smartbanner.min.js have a problem.
When I use smartbanner.min.js "X" button can not show. 
But When I use smartbanner.js "X" button show normally.
Thanks for reading. :)

**Comment by ain** [comment]
Thanks for the report. Could you please specify the exact platform you're running it on?

**Comment by havudk1707** [comment]
I'm running in iOS and Safari.
Webserver is AWS Ubuntu

**Comment by ain** [comment]
iOS is rather heavily tested, I'd suspect some implementation (CSS) error. Are you on iOS 9?

**Comment by ain** [comment]
No response, closing. 

Please feel free to call for reopening the issue by answering the above concerns.
