### ISSUE TITLE
Uncaught Error: Cannot find module "smartbanner.js"

### ISSUE THREAD

**Issue by dbustard** [ain/smartbanner.js#100]
__Steps to reproduce__:

1. add require('smartbanner.js');
__What happens__: getting error Uncaught Error: Cannot find module "smartbanner.js"

__What should happen__:
we need to add require('smartbanner.js') so that webpack will see that smartbanner used and will be added to uglify. 

not sure if i am using it right :) please help

**Comment by dbustard** [comment]
found solution

**Comment by ain** [comment]
Thanks for clarifying @dbustard!

The best course of action would be to work with distribution, e.g. `dist/smartbanner.js`, where all resources are already compiled and ready to use.

**Comment by Jorijn** [comment]
@dbustard it would be better if you would share your solution with other coming here from Google.
