### ISSUE TITLE
The banner is NOT displayed in IPad mini 3 and 2 

### ISSUE THREAD

**Issue by gracielaPosadas** [ain/smartbanner.js#107]
Testing the banner in browserStack with  IPad mini 3 and 2  the banner is not displayed, it works fine with the rest of the devices.

**Comment by gracielaPosadas** [comment]
Seems like it's not working for IOS 8 or older

**Comment by ain** [comment]
Could you please post your metadata you're using?

**Comment by gracielaPosadas** [comment]
Here is my metadata
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="smartbanner:title" content="Download the app">
  <meta name="smartbanner:author" content=" ">
  <meta name="smartbanner:price" content=" ">
  <meta name="smartbanner:price-suffix-apple" content="Apple and the Apple logo are trademarks of Apple Inc., registered in the U.S. and other countries.<br/>  App Store is a service mark of Apple Inc., registered in the U.S. and other countries.">
  <meta name="smartbanner:price-suffix-google" content="Google Play and the Google Play logo are trademarks of Google LLC.">
  <meta name="smartbanner:icon-apple" content="assets/AppIcon640.png">
  <meta name="smartbanner:icon-google" content="assets/AppIcon640.png">
  <meta name="smartbanner:button" content="">
  <meta name="smartbanner:button-url-apple" content="https://itunes.apple.com/us/app/fepblue/id1217984963?ls=1&mt=8 ">
  <meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=com.bcbsa.fepblue">
  <meta name="smartbanner:enabled-platforms" content="android,ios">

**Comment by gracielaPosadas** [comment]
I found the issue, the smartbanner.js file it's using Array.from which is not working in IOS 8 or older I just update that for  Array.apply and that works.

**Comment by ain** [comment]
@gracielaPosadas did you use the files from `/dist` folder in your project?

**Comment by gracielaPosadas** [comment]
yes I used those @ain

**Comment by ain** [comment]
Reproduced:

```
TypeError: undefined is not a function (evaluating 'Array.from(metas)')
```
