### ISSUE TITLE
RegEx for URL

### ISSUE THREAD

**Issue by christian-hero** [ain/smartbanner.js#115]
Hello, i wont to exclude the Banner on a defined URL like www.domain.de/umfragen/umfragen-app
I use this but nothing will work.

`<meta name="smartbanner:exclude-user-agent-regex" content="^.*/umfragen/umfragen-app$">`

Kann you help?

**Comment by ain** [comment]
What you're trying to achieve is currently not possible by using the meta tags.

The code you've used avoids showing Smart App Banner on a certain User Agent, a browser, e.g. Chrome or Safari. It is not meant to work for anything else than that.

If you'd like to exclude `smartbanner.js` on a certain page, it's best to not to publish the meta tags on that page and exclude the JS/CSS in general. It'd be a good practice and you'd have positive impact on your page load and rendering.
