### ISSUE TITLE
hide path option 

### ISSUE THREAD

**Issue by meenss** [ain/smartbanner.js#117]
__Steps to reproduce__: We are using ember for our web application. We are embedding smartbanner.js in our ember app. Whereas I wanted to show in one of our ember engine and not on the main ember application where index.html is present

__What happens__: When I use hide-path option
`<meta name="smartbanner:hide-path" content="/">`
 It is not hiding at all, the smart banner appears on index and other html pages

__What should happen__: It should show only for the below path
`<meta name="smartbanner:hide-path" content="/example/page/showthis">
`

**Comment by ain** [comment]
Thanks for the interest.

Just to reiterate on 1914a04: `hide-path` is meant to control _smartbanner.js_ behaviour __once user has closed it__. It will not affect how _smartbanner.js_ will operate out of the box. See [updated  README](https://github.com/ain/smartbanner.js#path-designated-close).

If you'd like to avoid rendering it on some pages, just make sure to remove its meta tags from the markup.

**Comment by meenss** [comment]
@ain Thanks for an update. Ember single page application has routes defined for each page (hbs template) and it is handled/served through one index.html for the entire journey flow. 

In this case, I need to show smartapp banner in one of the route and hide in the other route of single page application. Do you have any suggestions on this please?

**Comment by ain** [comment]
If you can not work conditionally with the meta tags, you could simply use CSS and hide `.smartbanner` (or `.js_smartbanner` when JS-bound) in places where you need to omit it.
