### ISSUE TITLE
hiding smart banner for in-app browser

### ISSUE THREAD

**Issue by LCallaghan84** [ain/smartbanner.js#125]
<meta name="smartbanner:include-user-agent-regex" content=" ">

how do I hide the smart banner for in-app browser. 
is there a way to just put WebView UA or does it have to be specific?

**Comment by ain** [comment]
WebView implementations have been successfully completed before, and in your case I'd look into [hiding smartbanner by the user agent string](https://github.com/ain/smartbanner.js#hide-the-smartbanner-for-certain-user-agents) or leveraging the brand new [API](https://github.com/ain/smartbanner.js#smartbanner-api-use) that was released today.
