### ISSUE TITLE
Whitespace after closing the banner on iPad 7th Gen. iOS 13

### ISSUE THREAD

**Issue by endcoreCL** [ain/smartbanner.js#131]
__Steps to reproduce__:

1. Close the smartbanner on an iPad 7th Gen. with newest iOS 13

__What happens__:
A blank whitespace appears

You can test it here: https://www.onlinesolutionsgroup.de/

**Comment by ain** [comment]
Thanks for the report @endcoreCL! 

https://www.onlinesolutionsgroup.de does not seem to bring up the Smart Banner at all. 

In order to reproduce, could you please post your markup and/or smartbanner.js API-related code here?

**Comment by endcoreCL** [comment]
Hey,

we use this code:

`<meta name="apple-itunes-app" content="app-id=1222858824">
<meta name="smartbanner:title" content="OSG Performance Suite">
<meta name="smartbanner:author" content="Online Solutions Group GmbH">
<meta name="smartbanner:price" content="LADEN">
<meta name="smartbanner:price-suffix-google" content=" - In Google Play">
<meta name="smartbanner:icon-google" content="https://www.onlinesolutionsgroup.de/fileadmin/osg2015/admin/img/osg-smartbanner-icon.png">
<meta name="smartbanner:button" content="Anzeigen">
<meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=de.onlinesolutionsgroup.reportingcenter&hl=de">
<meta name="smartbanner:button-url-apple" content="https://apps.apple.com/us/app/osg-reporting-center/id1222858824?l=de&ls=1">`

The banner works on our iOS Devices, can u retry it? Maybe there was a old cache, i cleared it.

**Comment by endcoreCL** [comment]
Holy.. sorry. I recognized that we only use the smartbanner for android. The bug comes from the build-in banner from ios. Sorry dude.

Now we want use smartbanner.js on iOS too. The event "smartbanner.view" will not fire? 

`document.addEventListener('smartbanner.show', function() {
	jQuery('body').addClass('smartbanner-show');
});`

I need to set a class to body, to get the banner above our sticky header.
