### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by jasonejavier** [ain/smartbanner.js#133]
I already added all the meta tags, css, and script. The banner isn't showing. Any help?

**Comment by ain** [comment]
Thank you for the report.

Could you please copy your meta tags here for further investigation?
-- 
Sent from Gmail Mobile

**Comment by jasonejavier** [comment]
Hi. Just a question. Is it running under development server?

**Comment by jasonejavier** [comment]
`<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
  <meta http-equiv="Cache-control" content="no-cache, no-store, must-revalidate">
  <meta http-equiv="Pragma" content="no-cache">
  

  <meta name="robots" content="INDEX,FOLLOW" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta property="og:type"        content="website" />
  <meta name="theme-color"    content="#000000">

  
  <meta name="smartbanner:title" content="
Luxe In">
  <meta name="smartbanner:author" content="PawnHero Pawnshop">
  <meta name="smartbanner:price" content="FREE">
  <meta name="smartbanner:price-suffix-apple" content=" - On the App Store">
  <meta name="smartbanner:price-suffix-google" content=" - In Google Play">
  <meta name="smartbanner:icon-apple" content="images/banner_logo_install.png">
  <meta name="smartbanner:icon-google" content="images/banner_logo_install.png">
  <meta name="smartbanner:button" content="VIEW">
  <meta name="smartbanner:button-url-apple" content="https://apps.apple.com/ph/app/luxe-in/id1469197978?mt=8">
  <meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=com.luxein.app">
  <meta name="smartbanner:enabled-platforms" content="android,ios">
  <meta name="smartbanner:close-label" content="Close">

  <link rel="stylesheet" href="../node_modules/smartbanner.js/dist/smartbanner.min.css">
  <script src="../node_modules/smartbanner.js/dist/smartbanner.min.js"></script>
  
`

Hi these are my meta tags and the script that I had copied and pasted from here

**Comment by ain** [comment]
@jasonejavier thanks. Are you sure that `../node_modules/smartbanner.js/dist/smartbanner.min.js` is actually being loaded? 

You can run `dist/index.html` locally in order to see how it runs or you can also do `npm start` in project home (does the same thing).

**Comment by rickibarnes** [comment]
Did we ever find a solution to this? I am having the same problem - it doesn't plug and play.

When I run dist/index.html locally nothing happens either - will it work in the desktop browser?
