### ISSUE TITLE
Are you open to a style tweak PR?

### ISSUE THREAD

**Issue by RyanTG** [ain/smartbanner.js#141]
Thanks for the great tool!

I added it to my [my site](https://pinballmap.com/), but am going to tweak the style slightly to be closer to other smart banners I’ve seen. [Like this one.](https://www.garagejournal.com/forum/showthread.php?t=409988) 

- Bigger line height
- Some gray text
- Smaller “VIEW” font 

Maybe more little things. I’ll do it for my own site, and can submit a PR, too, if you’re open to it.

**Comment by ain** [comment]
Changing default styles is not really a good idea due to legacy issues and impact on current users who'd expect consistent behaviour across upcoming versions.

Nevertheless, feel free to implement on your sites with custom styles.

**Comment by RyanTG** [comment]
K. 

I did it on my site. All I did was adjust the padding, since the lines of test are so compacted. And made the bottom two lines of text gray. Looks much better!
