### ISSUE TITLE
smart app banner not showing on iOS and Android!

### ISSUE THREAD

**Issue by shaikhah-sdc** [ain/smartbanner.js#147]
Hi

I just tried to use this package but didn't work for some reason I can't figure it out.

<img width="330" alt="Screen Shot 1441-09-22 at 02 10 49" src="https://user-images.githubusercontent.com/64577714/81994794-52916880-9651-11ea-8e03-a8adccb62bdb.png">

Here's the meta tags
```
<!-- Start SmartBanner configuration -->
<meta name="smartbanner:title" content="SDC Application">
<meta name="smartbanner:author" content="Special discounts and offers">
<meta name="smartbanner:price" content="FREE">
<meta name="smartbanner:price-suffix-apple" content=" - On the App Store">
<meta name="smartbanner:price-suffix-google" content=" - In Google Play">
<meta name="smartbanner:icon-apple" content="{{ asset('favicon/android-chrome-192x192.png') }}">
<meta name="smartbanner:icon-google" content="{{ asset('favicon/android-chrome-192x192.png') }}">
<meta name="smartbanner:button" content="VIEW">
<meta name="smartbanner:button-url-apple" content="https://apps.apple.com/sa/app/sdc-cards/id1125813714">
<meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=com.dl.sdccards">
<meta name="smartbanner:enabled-platforms" content="android,ios">
<meta name="smartbanner:close-label" content="Close">
<!-- End SmartBanner configuration -->
```

And I'm sure about the css and js loading, you can check [here](https://test.sdccards.com/) as well, here's the [css](https://test.sdccards.com/assets/css/app.css?id=3f195d8bcd4c002ee8a5) and [js](https://test.sdccards.com/js/all.js?id=5c201208770105740a36) to check them your self if needed. 

I would appreciate your help!

**Comment by shaikhah-sdc** [comment]
apparently it's showing in a wrong position and some of the style is not working properly (app meta with View word), I placed the css file at the very end in my application so it's strange to behave like this. 
<img width="325" alt="Screen Shot 1441-09-22 at 13 00 30" src="https://user-images.githubusercontent.com/64577714/82038828-c90f8400-96ac-11ea-84e5-31970474b570.png">

I'm wondering if there's a way to debug the issue in my desktop device? so making the banner showing in all devices not just mobiles

**Comment by ain** [comment]
Thanks for the report @shaikhah-sdc,

This looks as a CSS malfunction where the main site conflicts with the styles of the smartbanner.js. Make sure your CSS/JS is included in the `<head>` of the page. 

Let me know if that works out.

**Comment by shaikhah-sdc** [comment]
Hi @ain 
Yup I figured it out, it was a style issue with the main nav/app banner positions. I fixed it by adding customizable css. 

 Thanks for your reply 👍
