### ISSUE TITLE
Hiding when scrolling down

### ISSUE THREAD

**Issue by kkristof200** [ain/smartbanner.js#15]
Hey,

First of all I really like your work and thanks a lot for making it!
Since I'm not a web dev, I only understand the code so and so, but I want to implement a "hide/show" feature depending on the scrolling direction. I've googled a lot, but couldn't really solve the problem, so I thought that the best solution would be posting a question here.
Here is a link to show what do I want exactly:
http://jsfiddle.net/mariusc23/s6mLJ/31/

Thanks a lot,
Kristof Kovacs

**Comment by ain** [comment]
Thanks for the question @kkristof200.

Interesting request and I can see the use case. I'm mixed about possible implementation though as it'd be wrong to add another responsibility to `smartbanner.js` esp. considering the level of complexity that libraries like [skrollr](https://github.com/Prinzhorn/skrollr) or [ScrollMagic](https://github.com/janpaepke/ScrollMagic) have to offer.

I'm more trending towards open API approach that'd allow interaction with `smartbanner.js` so one could add ScrollMagic to their project and call smartbanner hide/show from ScrollMagic handlers accordingly.

As for the current workaround you could work with the `smartbanner` div element already and implement its hiding by working with the container div directly from ScrollMagic.

**Comment by kkristof200** [comment]
Thank you a lot for your fast response! Keep it up! :D
