### ISSUE TITLE
How to set this up with wordpress?

### ISSUE THREAD

**Issue by clmanalo** [ain/smartbanner.js#150]
I was looking for a cross browser app banner tool and i found this. it looks like it will work for the requirement i need for app banners for mobile safari and chrome. Do i just add this to the root of my wordpress app and add the meta tags, javascript, and css as defined in the [basic usage](https://github.com/ain/smartbanner.js/blob/master/README.md#basic-usage) section and it should work automagically?

thanks

**Comment by clmanalo** [comment]
i tried installing it but i enountered the same issue here

https://github.com/ain/smartbanner.js/issues/133

the CSS and JS are being loaded but the banner is not appearing

**Comment by ain** [comment]
Thanks for the ticket @clmanalo. 

If JS/CSS is loaded from `dist/` folder of smartbanner, some questions/advice:

1. With the Inspector, inspecting your page, can you locate a `div` element that has `smartbanner` class, e.g. `<div class="smartbanner"...`? If you can, check that it has not been hidden by your CSS
2. Do you have any errors on console?
3. Please also post your meta tags
