### ISSUE TITLE
Z-index of smart banner should be set higher

### ISSUE THREAD

**Issue by josheche** [ain/smartbanner.js#17]
Bootstrap 4 nav with high z-index needs workaround with the smart banner. Smart banner element stays behind the navbar. Fix was to set value of smart banner z-index to '9999'.

**Comment by ain** [comment]
`smartbanner.js` was not meant to overlap or work with `z-index`, it was meant to push content down and let content come up again if closed. It works like this on jQuery Mobile. 

In other frameworks one can either work with CSS or I'd also welcome a contribution that solves it for the framework :)
