### ISSUE TITLE
How to use it with nuxt.js

### ISSUE THREAD

**Issue by CavalcanteLeo** [ain/smartbanner.js#236]
Hey guys, is it possible to integrate it with nuxt.js?

If yes, can anyone help me showing how?

I tried this:

nuxt.js
```js
head: {
  meta: [
    { name: 'smartbanner:title', content: '3,2,1 Beauty' },
    { name: 'smartbanner:author', content: '3,2,1 Beauty' },
    { name: 'smartbanner:price', content: 'FREE' },
    { name: 'smartbanner:price-suffix-google', content: ' - In Google Play' },
    { name: 'smartbanner:icon-google', content: '/assets/img/logo-rgb.png' },
    { name: 'smartbanner:button', content: 'VIEW' },
    {
      name: 'smartbanner:button-url-google',
      content:
        'https://play.google.com/store/apps/details?id=br.com.beauty321.app',
    },
    {
      name: 'smartbanner:button-url-apple',
      content: 'https://apps.apple.com/br/app/3-2-1-beauty/id1525220986',
    },
    { name: 'smartbanner:enabled-platforms', content: 'android,ios' },
  ],
  script: [
    { src: '/meta/js/smartbanner.js', defer: true },
  ],
}

```

it shows in the HTML:
<img width="1086" alt="Captura de Tela 2021-01-06 às 12 24 09" src="https://user-images.githubusercontent.com/1735944/103785564-1cf32280-501a-11eb-95d6-b9408ed6a1d3.png">

the link `/meta/js/smartbanner.js` is valid....

but didn't work

you can check it out here:
https://site-stg.321beauty.com.br/

**Comment by CavalcanteLeo** [comment]
my bad, i forgot to import the style, it was at the bottom of the page

**Comment by ain** [comment]
Thanks for the heads up @CavalcanteLeo!
