### ISSUE TITLE
close button is not working for firefox and UC browser on android

### ISSUE THREAD

**Issue by abhishekoswal** [ain/smartbanner.js#25]
Hi,
thank you for such a wonderful  banner
this app install banner is working as expected on chrome but the close button is not working for firefox
also sometime the close button is not appearing on UC browser but if you touch on left it is able to close 
if you can suggest me anything which help to solve the problem 

thanks,

**Comment by ain** [comment]
I've just tested on `iOS Firefox 5.3 (2)` and it worked as expected.

You can compare your implementation to `dist/index.html` and see if you can reproduce the problem there as well. If you can, it is a component problem so I'd kindly ask you to provide more details about your platform. If not, it's an implementation problem.

As for implementation advice, look into your (S)CSS for any rules that might cause the malfunction.

**Comment by MatasSim** [comment]
Hi, Ain. there`s an issue with close button. 
<img width="578" alt="screen shot 2017-01-31 at 2 59 40 pm" src="https://cloud.githubusercontent.com/assets/9293338/22465791/1acd4816-e7c6-11e6-9ec1-1eca8a1bf978.png">

Also I have one more question. 
How could I disable this plugin? If my page does not have meta tag?
error mesaage: 
<img width="395" alt="screen shot 2017-01-31 at 3 03 30 pm" src="https://cloud.githubusercontent.com/assets/9293338/22465881/75a97b6a-e7c6-11e6-9c0c-80a1818d3f96.png">

**Comment by ain** [comment]
@MatasSim `smartbanner.js` initialises automatically whenever JavaScript is included on page. Just make sure that you don't include JavaScript if you don't have meta tags on page.

**Comment by MatasSim** [comment]
thanks for fast reply. we are using your plugin in rails app. Script is automatically loaded from vendor. In some cases we don`t want to show smartbanner. Anyway, thank`s for the plugin, we'll try to find out the solution and I will let you know

**Comment by ain** [comment]
@MatasSim I see. You can go for a conventional change by always keeping the meta tags and apply [Advanced usage](https://github.com/ain/smartbanner.js#advanced-usage) for UA-based filtering in scenarios you don't need the `smartbanner.js` to show up.

**Comment by fkoester** [comment]
Had the same problem, fixed using patch from PR https://github.com/ain/smartbanner.js/pull/32

**Comment by ain** [comment]
Thanks to @fkoester, fix landed in `1.4.1`.
