### ISSUE TITLE
Can we set cookie expires time

### ISSUE THREAD

**Issue by aspmaker** [ain/smartbanner.js#28]
Hello. Can we set cookie value (smartbanner_exited)  in js code ? Example i want to show banner every 15 day and only one time. Thank you.

**Comment by ain** [comment]
Hi @aspmaker, thank you for your interest.

Currently not. At the moment `smartbanner.js` cookie behaviour mocks the original Apple Smart App banner behaviour by creating a cookie as per browser session.

Nevertheless, I can't see any arguments against such feature and I can see your use-case. I'd gladly accept your Pull Request with this feature.

Before you start, please see [contribution guidelines](https://github.com/ain/smartbanner.js/blob/master/CONTRIBUTING.md) and make sure you add tests against your feature.

**Comment by Igor10k** [comment]
@ain Apple docs state that banner won't reappear, so cookie per session doesn't mock the original behavior.

from https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html:
> When the user returns to the webpage, the banner won’t reappear.

**Comment by ain** [comment]
@Igor10k you're probably right. Nevertheless, it's not a good idea to change this behaviour due to legacy reasons, but I'd be more than glad to merge a reasonable PR on this.

**Comment by ain** [comment]
Landed in [v1.6.0](https://github.com/ain/smartbanner.js/releases/tag/v1.6.0).
