### ISSUE TITLE
Doesn't work in embedded Android browser

### ISSUE THREAD

**Issue by leshik** [ain/smartbanner.js#3]
Smart Banner doesn't work in embedded Android browser on any version of OS. What can be the cause of that?

**Comment by ain** [comment]
Thanks for the report.

smartbanner.js has been tested to work with:

- Android 6 (Samsung Galaxy S7, Nexus 6, Moto X 2nd gen)
- Android 5 (Samsung Galaxy S6)
- Android 4.4 (Samsung Galaxy S5)

Could you please specify your platform and/or double-check if all the meta tags are properly set? It could be that the Android-specific data that is needed, is missing.

**Comment by ain** [comment]
One more clarification, by meaning embedded browser, you mean the WebView? 

smartbanner.js relies on `window.load` event in order to push itself to the DOM. Maybe that is something to do with it?

**Comment by leshik** [comment]
Sorry for the delay. By the embedded browser I mean one shipped with the default OS configuration, e.g. when you install emulator from Android Studio or Genymotion.

**Comment by ain** [comment]
Emulators are generally known to be unreliable. Default browsers definitely work.

`1.0.2` that was released just yesterday got retested on actual device, Samsung Galaxy S7 with Android 6.

Could you try running it without the emulator on actual device?

**Comment by azelensky** [comment]
Hi Ain, 

Thank you for the SmartBanner code. It is really the best available on internet.

But I can confirm, that it doesn't work on at least some Android default browsers (the ones which come with clean Android, I believe it is modified Chrome). 
- Android 5.1 (Meizu M2)

Waiting for the info from other testers and will pass it over.

We would very appreciate if you can check it and find the solution.

Thanks

[Browser details attached] 
![s60816-110956](https://cloud.githubusercontent.com/assets/21055071/17694574/ca1b1d94-63a4-11e6-9aa4-470ea279a012.jpg)

**Comment by ain** [comment]
Thank you for the details @azelensky. 

I've confirmed the problem on an emulator myself now and despite the fact that smartbanner.js was never built to support emulators, I'll leave this ticket in here as an enhancement and see if there's an easy fix to be done.

**Comment by leshik** [comment]
@ain I think @azelensky was talking about real device (Meizu M2), not an emulator. In my case, the device that I own have Chrome already preinstalled as default browser, thus I can test this case only on emulator. Therefore I'd like to thank @azelensky for his input and also thank you for considering this enhancement!

**Comment by azelensky** [comment]
@ain , thank you for checking this out.

This issue happens NOT on emulators, but on real physical device (Meizu M2). Also we have external testers on real devices as well and they confirmed the issue.

One more device details:
- GIGABYTE Gsmart Maya M1 v2 (Android 4.2.1)

It works fine on Chrome (installed from Google Play), but doesn't work on default browser, installed on device by default.

**Comment by ain** [comment]
Yes, I've confirmed the problem and it relates to all old Android versions. Fix is already in the works.

**Comment by azelensky** [comment]
Perfect. Thanks a lot

**Comment by leshik** [comment]
@ain Thank you.
I've made some tests. It works as expected on Android 4, starting from JellyBean 4.2. There is one issue on Android 5 and 6, however - the app icon isn't shown.
![Lollipop & Marshmallow](https://cloud.githubusercontent.com/assets/443678/17834125/d5917158-6743-11e6-995b-4ab53bc3cf40.png)

**Comment by ain** [comment]
@leshik is your `smartbanner:icon-google` meta tag properly set? Is the image otherwise reachable?

My tests on both platforms were successful and this change didn't touch icon handling.

**Comment by leshik** [comment]
@ain Thank you for the hint! I finally figured it out. I tested the default example from dist/ directory and put it on https-enabled server. I changed smartbanner:icon-google url to https and now it works. It was mixed content issue, definitely.

**Comment by ain** [comment]
Glad it worked out, best of luck with your project!

**Comment by azelensky** [comment]
@ain , thank you very much. It works on all our test devices.

It is the best smart banner code on internet and just life saving for us.

Thank you again for sharing!
