### ISSUE TITLE
Not able to run this project locally

### ISSUE THREAD

**Issue by reetkamleshpoptani** [ain/smartbanner.js#342]
__Steps to reproduce__:

1. Did npm install
2. Did npm run build
3. Did npm start

__What happens__: I get error as below :
npm start    

> smartbanner.js@1.16.0 start C:\Users\reet.kamlesh.poptani\adobe projects\smartbanner.js-master\smartbanner.js-master
> ws --spa dist/index.html --port=8080

C:\Users\reet.kamlesh.poptani\adobe projects\smartbanner.js-master\smartbanner.js-master\node_modules\local-web-server\bin\cli.mjs:2
import WsCli from '../lib/cli-app.mjs'
       ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smartbanner.js@1.16.0 start: `ws --spa dist/index.html --port=8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smartbanner.js@1.16.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\reet.kamlesh.poptani\AppData\Roaming\npm-cache\_logs\2021-07-28T06_43_46_529Z-debug.log

__What should happen__: The project should run locally without any errors

Please provide urgent help. I need this functionality ASAP

**Comment by ain** [comment]
Thank you for the report.

smartbanner has been developed on a UNIX-compatible system and therefore using Windows for development may also be troublesome.

Nevertheless, `local-web-server` has been upgraded to the most recent version on `master`.

You can test the most recent version from `master` branch or just open the file in the browser as a workaround.
