### ISSUE TITLE
Can't set cookie for subdomain

### ISSUE THREAD

**Issue by mike-irizarry** [ain/smartbanner.js#355]
How would I enable the smartbanner cookie to be set across subdomains? For instance:
site.com
subdomain.site.com

**Comment by ain** [comment]
Thanks for a question.

Currently only [path-designated closing](https://github.com/ain/smartbanner.js#path-designated-close) is possible on the same domain. 

I could imagine a feature, e.g. a boolean setting of `smartbanner:hide-base-domain` which would then affect all subdomains.

Your Pull Request with such a feature would be welcome, please also add tests if you decide to do it.
