### ISSUE TITLE
Pop-up blocked

### ISSUE THREAD

**Issue by remoteboy** [ain/smartbanner.js#368]
Switching back to Chrome on Android after clicking on the OPEN button produces a system alert. 

__Steps to reproduce__:

1. Open a website with smartbanner.js installed in Chrome on Android.
2. Click on the OPEN button
3. Play Store app opens on correct page
4. Return to Chrome Web Browser

__What happens__:
A message appears on the page saying 'Pop-up blocked'

__What should happen__:
No message should appear

**Comment by ain** [comment]
Thanks for the report @remoteboy!

Could you please specify:

- smartbanner version you used
- Android and Chrome version you used
