### ISSUE TITLE
Windows 10 on nokia phone show Google Play

### ISSUE THREAD

**Issue by geniovi** [ain/smartbanner.js#37]
hello,
i have a device NOKIA 1520 with Windows 10 and show banner..
i add
<meta name="smartbanner:enabled-platforms" content="android">
but not it works.
please fix

**Comment by ain** [comment]
Windows Mobile is officially not supported. It also says so in the description of the component.

Nevertheless, work on Windows Store support was started in PR #12, but has not been finished. You're welcome to either finish that PR or follow [Advanced usage](https://github.com/ain/smartbanner.js#advanced-usage) as it might also offer you a solution.

**Comment by geniovi** [comment]
in a windows 10 mobile show smartbanner.
i added
<meta name="smartbanner:enabled-platforms" content="android">
<meta name="smartbanner:exclude-user-agent-regex" content="MSIE ([0-9]{1,}[\.0-9]{0,})">

but not it works.
how should I do? it is bad that on windows devices show the banner of Android app installs
