### ISSUE TITLE
Customizable placement of smartbanner html

### ISSUE THREAD

**Issue by pre2612** [ain/smartbanner.js#399]
__Steps to reproduce__:

1.Code inserts smartappbanner in body, it would be nice if we have can have flexibility to enter it in certain element.
2.
3.

__What happens__: 

__What should happen__:

**Comment by ain** [comment]
There are multiple reasons for Smart App Banner's opinionated positioning:

- keeping component robust and not deviate too much from the promise of mimicking the original Smart App Banner
- driving efficient conversion for the adoption of the mobile app. Component's location above the fold is desirable and expected by most users

On these grounds I'm closing the requests, but with a note that there are positioning-related changes considered, e.g. in #279.
