### ISSUE TITLE
Does it work in React? For me it is not showing

### ISSUE THREAD

**Issue by caiogmar** [ain/smartbanner.js#407]
In React I followed the simple instructions, added the JS library and CSS, yet it doesn't show. Does it support React?

**Comment by Akeembrisc0** [comment]
yea i have the same issue, the banner wont show up in my react app

**Comment by ain** [comment]
There's no React support per se.

You can try to instrument by using [API guidance](https://github.com/ain/smartbanner.js#smartbanner-api-use).

Alternatively, you're very welcome to [contribute a Pull Request](https://github.com/ain/smartbanner.js#contributing).
