### ISSUE TITLE
Bug in a Microsoft Edge in a windows phone mobile

### ISSUE THREAD

**Issue by geniovi** [ain/smartbanner.js#41]
hello,
i'm configured your component in a my site.
this is a my configuration

meta name="smartbanner:title" content="My Title name">
meta name="smartbanner:author" content="My Company">
meta name="smartbanner:price" content="Free">
meta name="smartbanner:price-suffix-google" content=" - In Google Play">
meta name="smartbanner:icon-google" content="smartbanners/appIcon.png">
meta name="smartbanner:button" content="View">
meta name="smartbanner:button-url-google" content="app url">
**meta name="smartbanner:enabled-platforms" content="android">**

if i open my site in a Windows 10 mobile (browser edge) show banner.. why?
later I also tried to add:

meta name="smartbanner:exclude-user-agent-regex" content="MSIE ([0-9]{1,}[.0-9]{0,})"

but not it works.
how should I do? it is bad that on windows devices show the banner of Android app installs
thanks

**Comment by geniovi** [comment]
resolved. i add this: 

meta name="smartbanner:exclude-user-agent-regex" content="Windows Phone\s([0-9]{1,}[.0-9]{0,})"

**Comment by ain** [comment]
@geniovi thanks for updating the information and how you resolved it. It will be helpful for others.

Let's keep the issue open for now, I want to test your reported behaviour and confirm the bug, if there is one.

**Comment by ain** [comment]
Even without `exclude-user-agent-regex` I could not reproduce the problem. Banner stays hidden.

Tested on Nokia Lumia 520 and 930 with Windows Phone 8.1.
