### ISSUE TITLE
Smart Banner isn't showing up on Safari and Chrome

### ISSUE THREAD

**Issue by inazrabuu** [ain/smartbanner.js#43]
Hello,

Just cloned and deployed your script to my mobile site. It worked when I tried to view the site from desktop browser using user agent changer on Chrome. But it didn't worked when I tried to view it from actual iPhone and Android device.

Do you know what might be the problem?

**Comment by ain** [comment]
@inazrabuu thanks for the report.

Are you using a regular expression to target platforms or are you using the default non-advanced behaviour? 

Please provide your meta tags so the issue can be identified.

**Comment by inazrabuu** [comment]
Hello, thank you for replying, here is my meta codes:


    <meta name="smartbanner:title" content="Female Daily Beauty Review">
    <meta name="smartbanner:author" content="Female Daily Network">
    <meta name="smartbanner:price" content="FREE">
    <meta name="smartbanner:price-suffix-apple" content=" - On the App Store">
    <meta name="smartbanner:price-suffix-google" content=" - In Google Play">
    <meta name="smartbanner:icon-apple" content="https://s3-ap-southeast-1.amazonaws.com/assets.femaledaily.com/images/fd_app_logo.png">
    <meta name="smartbanner:icon-google" content="https://s3-ap-southeast-1.amazonaws.com/assets.femaledaily.com/images/fd_app_logo.png">
    <meta name="smartbanner:button" content="VIEW">
    <meta name="smartbanner:button-url-apple" content="https://fdbr.onelink.me/nOPE?pid=web&c=smartbanner&af_dp=fdbr%3A%2F%2F&af_web_dp=http%3A%2F%2Fapp.femaledaily.com">
    <meta name="smartbanner:button-url-google" content="https://fdbr.onelink.me/nOPE?pid=web&c=smartbanner&af_dp=fdbr%3A%2F%2F&af_web_dp=http%3A%2F%2Fapp.femaledaily.com">
    <meta name="smartbanner:enabled-platforms" content="android,ios">

**Comment by ain** [comment]
Are you getting any errors on console?

**Comment by inazrabuu** [comment]
Hello, 

No error so far. It works when I tried to view on Desktop browser with mobile user agent. When I tried to view from mobile browser, it doesn't work. By the way, how can I view the console from mobile browser?

**Comment by ain** [comment]
Connect your iPhone over USB to the machine and select the device under _Develop_ to view the separate Inspector for it. 

It's a good question since that would give us feedback if you may in fact have a CSS problem that hides the `smartbanner`, meaning, that the markup is actually there, but not visible.

**Comment by ivan-rangel** [comment]
@inazrabuu I was experimenting the same issue, the meta tags were set correctly but the CSS was the problem. Take a look.

Cheers!!
