### ISSUE TITLE
Error when running "npm run install-deps"

### ISSUE THREAD

**Issue by theonicolaou** [ain/smartbanner.js#47]
When I run "npm run install-deps" I get this error (I am using npm 2.1.12 and I have tried "npm update" but this doesn't make a difference:

npm run install-deps

> smartbanner.js@1.5.0 install-deps /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> npm install && bundle install

npm WARN package.json smartbanner.js@1.5.0 scripts['server'] should probably be scripts['start'].
npm WARN package.json mocha@2.5.3 No README data
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
add-banner@0.1.0 node_modules/add-banner
├── xtend@3.0.0
├── parse-authors@0.1.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── strip-banner@0.1.1 (strip-comments@0.1.6)
├── template@0.2.1 (delims@0.1.4, lodash@2.4.2)
├── year@0.1.2 (frep@0.2.3)
└── load-pkg@0.1.0 (cwd@0.3.7)
sh: bundle: command not found

npm ERR! Darwin 16.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "install-deps"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
npm ERR! smartbanner.js@1.5.0 install-deps: `npm install && bundle install`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 install-deps script 'npm install && bundle install'.
npm ERR! This is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && bundle install
npm ERR! You can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js/npm-debug.log

**Comment by ain** [comment]
@theonicolaou yes, `smartbanner.js` requires [Bundler](http://bundler.io) for SCSS linting. 

Please install and rerun.

**Comment by theonicolaou** [comment]
Thanks @ain, installing Bundler did the trick. I think it would be helpful if this instruction (and how to lint the SCSS file) was included in the CONTRIBUTING.MD file. I have set up another PR for this (https://github.com/ain/smartbanner.js/pull/48)

**Comment by theonicolaou** [comment]
On a similar note, when trying to run:  "npm run build" I get a similar error:

> smartbanner.js@1.5.0 build /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise


> smartbanner.js@1.5.0 build:js /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> npm run browserify && npm run uglify


> smartbanner.js@1.5.0 browserify /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]

sh: browserify: command not found

npm ERR! Darwin 16.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "browserify"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
npm ERR! smartbanner.js@1.5.0 browserify: `browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 browserify script 'browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]'.
npm ERR! This is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]
npm ERR! You can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js/npm-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build:js"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
npm ERR! smartbanner.js@1.5.0 build:js: `npm run browserify && npm run uglify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 build:js script 'npm run browserify && npm run uglify'.
npm ERR! This is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run browserify && npm run uglify
npm ERR! You can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js/npm-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12
npm ERR! code ELIFECYCLE
npm ERR! smartbanner.js@1.5.0 build: `npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 build script 'npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise'.
npm ERR! This is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise
npm ERR! You can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js/npm-debug.log

Is there anything else that I need to have installed?

**Comment by ain** [comment]
@theonicolaou you're running a rather old Node.js of `v0.10.33`, but minimum is slightly higher, see https://github.com/ain/smartbanner.js/blob/master/package.json#L29

**Comment by theonicolaou** [comment]
Hi @ain I updated to the latest stable version of Node (7.10.0) but still get the following error when I run "npm run build":

> smartbanner.js@1.5.0 build /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise


> smartbanner.js@1.5.0 build:js /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> npm run browserify && npm run uglify


> smartbanner.js@1.5.0 browserify /Users/theonicolaou/Documents/websites/smartbannerjs/smartbanner.js
> browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]

sh: browserify: command not found

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "browserify"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! smartbanner.js@1.5.0 browserify: `browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 browserify script 'browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/index.js -o dist/smartbanner.js -t [ babelify --presets [ es2015 ] ]
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smartbanner.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/.npm/_logs/2017-05-31T18_30_43_945Z-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:js"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smartbanner.js@1.5.0 build:js: `npm run browserify && npm run uglify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 build:js script 'npm run browserify && npm run uglify'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run browserify && npm run uglify
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smartbanner.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/.npm/_logs/2017-05-31T18_30_43_969Z-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smartbanner.js@1.5.0 build: `npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smartbanner.js@1.5.0 build script 'npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smartbanner.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:js && npm run build:css && npm run autoprefix && npm run build:css-min && npm run bannerise
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smartbanner.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smartbanner.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theonicolaou/.npm/_logs/2017-05-31T18_30_43_994Z-debug.log

**Comment by ain** [comment]
I have just tested on `npm run build` on Node.js `v7.10.0` and it runs through nicely. Must be local problem.

Try complete reset of dependencies:

```sh
rm -rf node_modules && npm i
```

**Comment by theonicolaou** [comment]
Great - that did work and I was able to install the deps and run the build. Thanks 👍
