### ISSUE TITLE
Shift to Node.js based SCSS linter

### ISSUE THREAD

**Issue by ain** [ain/smartbanner.js#49]
Installation of RubyGems is not seamless and sets new non-standard requirements for dependency installation.

[sass-lint](https://github.com/sasstools/sass-lint) should be used instead with a matching linting configuration.

**Comment by wolfika** [comment]
Good idea! However, you might want to check out [Stylelint](https://github.com/stylelint/stylelint). I found it being a more elegant, modern solution to SCSS linting instead of `sass-lint`.
