### ISSUE TITLE
Smart Banner ios version displayed for touch screen enabled desktops 

### ISSUE THREAD

**Issue by omkarvijf41** [ain/smartbanner.js#503]
__Steps to reproduce__:

Here is the config used to render smartbanner
`<meta name="smartbanner:title" content="Retire App” />
  <meta name="smartbanner:author" content="Services Company" /> 
  <meta name="smartbanner:price" content="FREE" />
  <meta name="smartbanner:price-suffix-apple" content=" - On the App Store" />
  <meta name="smartbanner:price-suffix-google" content=" - In Google Play" />
  <meta name="smartbanner:icon-apple" content="https://images-na.ssl-images-amazon.com/images/I/61YNOCKXGNL.png" />
  <meta name="smartbanner:icon-google" content="https://images-na.ssl-images-amazon.com/images/I/61YNOCKXGNL.png" />
  <meta name="smartbanner:button" content="GET" />
   <meta name="smartbanner:button-url-apple" content="https://apps.apple.com/us/app/voya-retire/id492157058" />
  <meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=com.ing.rs.ingretire&hl=en_US&gl=US" /> 
  <meta name="smartbanner:enabled-platforms" content="android,ios" />
  <meta name="smartbanner:close-label" content="Close" />
  <meta name="smartbanner:hide-ttl" content="10000">
  <meta name="smartbanner:api" content="true">
  <meta name="smartbanner:disable-positioning" content="true">
  <meta name="smartbanner:parent-element" content="#mobile-navigation.banner-container">
  <meta name="smartbanner:hide-path" content="/">
`
Here is the device details
navigtor.userAgent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'
navigator.platform is 'Win32' and device resolution is 1920 X 1080

__What happens__:
Smart Banner ios version displayed for touch screen enabled desktops chrome browser. I think the below snippet is causing this issue
https://github.com/ain/smartbanner.js/blob/15b64d1238ca73d5b2d0f466f5b14a7530b926b5/src/detector.js#L10 
 this becoming true and detected as iOS
__What should happen__:

Smartbanner should display for mobile android and ios platforms. Please let me know if any further details are required.

**Comment by antomed** [comment]
Same problem as described above. 
User agent details: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Original user agent (unchecked "Desktop site"): Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36
