### ISSUE TITLE
Platform-specific app titles for Android/ iOS

### ISSUE THREAD

**Issue by VirenMohindra** [ain/smartbanner.js#53]
Is there any way to create platform-specific titles if the android and iOS applications have different names?

I'm getting an `undefined` error when I try and create a new method for `title`

**Comment by ain** [comment]
Currently there's no such possibility. `title` works across all platforms.

I would advise extending `smartbanner.js` with a small JavaScript snippet that works based off `smartbanner--<platform>` class assigned to the main container and simply overwrites the title.
