### ISSUE TITLE
smartbanner.js@1.5.0: The engine "node" is incompatible with this module. Expected version "^6.2.0".

### ISSUE THREAD

**Issue by stanogurnik** [ain/smartbanner.js#57]
Using node v8.1.4. There is no reason to force using node 6

**Comment by ain** [comment]
There is. v8 is a major version which could mean a breaking change. `smartbanner.js` has not been tested on v8.

But I agree, we should upgrade this. Thanks for the ticket.

**Comment by duyleekun** [comment]
Tried to use with https://github.com/angulartics/angulartics2 which requires v8. Now stuck :)

**Comment by ain** [comment]
If tests go well I'll push a new release with v8 support over the weekend.

**Comment by duyleekun** [comment]
Yeah, it's not urgent since I can ignore the error with yarn :D I don't thing npm even check it :)
