### ISSUE TITLE
Why app banner is displaying in laptop screens, 1440 X 734 / 1366 X 768?

### ISSUE THREAD

**Issue by mukeshghodela-easternts** [ain/smartbanner.js#578]
__What happens__:
App banner is displaying in the some desktop screens. 
![image](https://user-images.githubusercontent.com/59353507/213623889-ae9aee0e-f801-4423-8e04-cfb17475f377.png)

__What should happen__:
App banner should not display in the desktop screens.

**Comment by ain** [comment]
Do you know if the desktop screen in question was a touchscreen?

**Comment by mukeshghodela-easternts** [comment]
> 

@ain Yes

**Comment by mukeshghodela-easternts** [comment]
@CametDean I have resolved it by using this regex: `^.*(Windows NT|Intel Mac OS X).*$`.

**Comment by CametDean** [comment]
Thank you !

**Comment by ain** [comment]
Possibly related to #503, needs investigation and a better solution.

**Comment by AndreasFurster** [comment]
I've the same issue. Also on a Windows 11 laptop with touch enabled. On Edge, Chrome and Firefox. 

```
Edge:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.69

Chrome: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

Firefox:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
```
