### ISSUE TITLE
min file no correctly exported?

### ISSUE THREAD

**Issue by lr-mjaouen** [ain/smartbanner.js#588]
__Steps to reproduce__:

1.look at the .min.js file in /dist
2.
3.

__What happens__:
I see this in the min file, is it normal?

```
artBanner},{"./bakery.js":1,"./detector.js":2,"./optionparser.js":4}]},{
```

__What should happen__:

one bundle?

**Comment by lr-mjaouen** [comment]
my bad it must be the source map?

**Comment by ain** [comment]
Last release was [v1.19.1](https://github.com/ain/smartbanner.js/releases/tag/v1.19.1) where `dist/smartbanner.min.js` is intact within the release package. It is also intact at https://github.com/ain/smartbanner.js/blob/main/dist/smartbanner.min.js

Please see [Basic usage](https://github.com/ain/smartbanner.js#basic-usage) for the implementation guidance.
