### ISSUE TITLE
Webpack warning when including the package

### ISSUE THREAD

**Issue by oquis** [ain/smartbanner.js#63]
When bundling an app using this package with webpack, a warning is thrown because it's best to include source files instead of preprocessed js files, which is not possible to do because the package doesn't include the sources files.

```
WARNING in ./~/smartbanner.js/dist/smartbanner.js
Critical dependencies:
5:113-120 This seems to be a pre-built javascript file. Though this is possible,
it's not recommended. Try to require the original source to get better results.
 @ ./~/smartbanner.js/dist/smartbanner.js 5:113-120
```

**Comment by ain** [comment]
You're free to work with `src/`. Distribution is included for convenience for those who would like to use the library directly.
