### ISSUE TITLE
Unexpected token ')' when close banner

### ISSUE THREAD

**Issue by jonayrodriguezmrf** [ain/smartbanner.js#642]
__Steps to reproduce__:

1. Click on close icon

__What happens__:
When I click the close button, I get the error `SyntaxError: Unexpected token ')'`, and it doesn't close. The next time, it closes

__What should happen__:
Close without error.

The problem is in the `javascript:void();`
It's missing the 0, `javascript:void(0);`
https://github.com/ain/smartbanner.js/blob/main/src/smartbanner.js#L136

**Comment by ain** [comment]
This is almost certainly the implementation issue of bundling smartbanner's source code (release code is tested and linted) in 3rd party applications, but since the change is harmless and could potentially avoid the problems you describe, there will be a release changing this.
