### ISSUE TITLE
Invisible App Icon

### ISSUE THREAD

**Issue by cgalatro2** [ain/smartbanner.js#650]
__What happens__: Icon seems to be present as it can be opened with a long press, but it's not showing up:

https://github.com/ain/smartbanner.js/assets/48544356/19f9c88d-7797-4299-8c36-39011595b6e6

__What should happen__: Icon's visible

Is this just a weird css issue?

Should be noted that I didn't follow your readme and instead followed [this guide](https://medium.com/umamitech-blog/smart-app-banners-for-ios-and-android-a-handmade-solution-7785d6bca205). I'm seeing this behavior on Chrome for iOS.

**Comment by ain** [comment]
smartbanner.js is built for the customisations in mind which also means that the implementation should follow the guidelines in the README of this repository.

I'd advise to follow the exact meta tags and also check that the image you're using is a standard image that all browsers can render.
