### ISSUE TITLE
Windows Convertibles are recognized as iOS devices

### ISSUE THREAD

**Issue by Micha95** [ain/smartbanner.js#658]
__Steps to reproduce__:

1.Try opening it with a Windows convertible

__What happens__:
Smartbanner detects the Windows convertible as iOS Device
__What should happen__:
Should Not be detected as iOS.

**Comment by ain** [comment]
Thanks for the report!

Could you please use your Windows convertible, go to https://duckduckgo.com/?q=user+agent and paste here what is shown in "Your user agent"? That'd help this discussion to go forward faster.

**Comment by ain** [comment]
@Micha95 if you have a moment, please report back 🙂
