### ISSUE TITLE
Accessibility concern with tabbing to banner

### ISSUE THREAD

**Issue by chriskim2311** [ain/smartbanner.js#686]
Order of tabbing should have banner first not further down the DOM tree. I suggest changing line 213 in smartbanner.js to `prepend` the div instead of `appendChild`

__Steps to reproduce__:

1. 
2.
3.

__What happens__:

__What should happen__:

**Comment by ain** [comment]
PR is welcome!

**Comment by chriskim2311** [comment]
@ain can you add my github username so I can push changes and add a PR?

**Comment by ain** [comment]
Please fork and send a PR from the fork. Please also add specs, see also the [contribution guidelines](https://github.com/ain/smartbanner.js/blob/main/CONTRIBUTING.md).

**Comment by chriskim2311** [comment]
Thanks @ain PR has been created https://github.com/ain/smartbanner.js/pull/692

**Comment by ain** [comment]
Landed in f3c79ee6c7266ea138a5376a79018f8e7a35ae65 for `v1.20.0`
