### ISSUE TITLE
smartbanner is visible on windows tab when enabled-platforms is set to android,ios

### ISSUE THREAD

**Issue by ramaces** [ain/smartbanner.js#687]
__Steps to reproduce__:

1. `<meta name="smartbanner:enabled-platforms" content="android,ios">`
2.
3.

i suppose to change line 77 on smartbanner.js into 
`} else if (!window.MSStream && !/X11|Linux|Windows/i.test(userAgent) && maxTouchPoints && maxTouchPoints > 0 || /iPhone|iPad|iPod/i.test(userAgent)) {`

__What happens__: smartbanner shows on windows tab device

__What should happen__: should only show on android and ios devices

**Comment by ain** [comment]
Thank you! 

@ramaces could you please post your User Agent string of the platform that you're seeing this problem on? This would be a good input for updating the specs.

**Comment by ramaces** [comment]
@ain 

Edge
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.57`

Chrome
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36`

**Comment by chriskim2311** [comment]
@ain Wanted to check in and see if we can merge this fix in. I am having this issue as well for windows touchscreen devices. Thank you so much!
