### ISSUE TITLE
Required content

### ISSUE THREAD

**Issue by Vitaliy-Opaynitch** [ain/smartbanner.js#695]
__Steps to reproduce__:

1. I need only one tag for display some text, without PRICE
2. I set "" (empty string) for meta tag <smartbanner:price>
3. I see text "undefined" on my banner

How I can fix it? I need just one tag for my text, author, title and price is required?

__What happens__: I see "undefined"

__What should happen__: I don't have to see this "undefined"

**Comment by ain** [comment]
`smartbanner:price` is documented as a mandatory field. When missing or empty`undefined` is expected.

Flagging as an enhancement.

**Comment by ain** [comment]
`v1.21.0` resolves your issue, please upgrade!

**Comment by Vitaliy-Opaynitch** [comment]
> `v1.21.0` resolves your issue, please upgrade!

Thank you)

**Comment by Vitaliy-Opaynitch** [comment]
@ain Does 1.21.0 version support integration with cdnjs?

**Comment by ain** [comment]
`cdnjs` is not up to date and does not have the latest version:

```
% curl https://api.cdnjs.com/libraries/smartbanner.js/1.21.0
{"error":true,"status":404,"message":"Version not found"}%   
```

As for why the latest version is not there yet, I do not know.

Nevertheless `smartbanner.js` is available from the [NPM](https://www.npmjs.com/package/smartbanner.js) and CDNs are not required for it to work. There's nothing in the code that either supports or does not support integrations over CDN.

**Comment by ain** [comment]
My recommendation would be to avoid the use of CDNs and work out the correct packaging strategy so HTTP round-trips and latencies from it can be avoided, improving page load and performance.
