### ISSUE TITLE
Incorrect cookie path

### ISSUE THREAD

**Issue by fvoordeckers** [ain/smartbanner.js#71]
__Steps to reproduce__:

1. go to a page with the banner that is not the root page of the site. Eg: `example.com/test/path/page`
2. hide de banner and refresh
3. the banner is not shown and the `smartbanner_exited` cookie is set correctly accept for the path. The path is set to `/test/path/page`
4. Go to a page that is lower in the page tree. Eg: `example.com/test` or `example.com` and the banner will popup again

__What happens__:
The incorrect path will allow the banners to show again on pages that are nog on `/test/path/page`. The homepage will show the banner or pages on another path as well. Only if a user visits the homepage fist and hides it there, the path will be set correctly.

__What should happen__:
If I hide the banner on one page of my site, it should be hidden everywhere. The path of the cookie should be the root of the site. Or even better, an extra smartbanner option.

## Additional info:
**Used smartbanner tags:**

`<meta name="smartbanner:title" content="My App">`
`<meta name="smartbanner:author" content="John Doe">`
`<meta name="smartbanner:price" content="FREE">`
`<meta name="smartbanner:price-suffix-apple" content=" - On the App Store">`
`<meta name="smartbanner:price-suffix-google" content=" - In Google Play Store">`
`<meta name="smartbanner:icon-apple" content="smartbanner-icon.png">`
`<meta name="smartbanner:icon-google" content="smartbanner-icon.png">`
`<meta name="smartbanner:button" content="VIEW">`
`<meta name="smartbanner:button-url-apple" content="itmss://itunes.apple.com/be/...">`
`<meta name="smartbanner:button-url-google" content="https://play.google.com/store/...">
`<meta name="smartbanner:enabled-platforms" content="android,ios">`

**Comment by fvoordeckers** [comment]
By adding the [path](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) to the cookie string this issue might be solved.

**Comment by ain** [comment]
Thanks for the report. This definitely deserves some investigation.

**Comment by ain** [comment]
@fvoordeckers thanks for the ticket!

For now the default behaviour has been retained, mainly due to legacy support. Nevertheless, this will change in `2.0.0`.

Please see [path-designated close](https://github.com/ain/smartbanner.js#path-designated-close) for more info.

**Comment by fvoordeckers** [comment]
@ain thanks for picking this one up in the next release

**Comment by fvoordeckers** [comment]
@ain just letting you know the path-designated close doesn't solve this issue (also changing the default valui in v2.0.0 will not solve it). 

The problem is that the cookie doesn't have a specified path and will therefore fallback to the current path. All the pages under the same path will act correctly, all pages on another path will show the banner again because the cookie path is different.

**Comment by ain** [comment]
It solves a problem for all paths if set to `/`. Default setting in `2.0.0` would disable showing smartbanner across the site.
