### ISSUE TITLE
Value for enabled-platforms

### ISSUE THREAD

**Issue by Vitaliy-Opaynitch** [ain/smartbanner.js#724]
__Steps to reproduce__:

1. Install smartbanner.js
2. Added tag 'smartbanner:enabled-platforms', content: 'none'

__What happens__: I don`t see the banner

__What should happen__: Can we use another value for this tag or just 'none'

I want use some conditions for show/hide banner on my platform

For example if I have isMobileApp === true => hide banner

**Comment by ain** [comment]
`enabled-platforms` is documented within [Basic usage](https://github.com/ain/smartbanner.js?tab=readme-ov-file#basic-usage) the default value of which is `andoird,ios` meaning that the `smartbanner.js` will work on both Android and iOS platforms.
