### ISSUE TITLE
Hide in Safari browser

### ISSUE THREAD

**Issue by saurabhSiddhu** [ain/smartbanner.js#74]
Is it possible  to hide smartbanner only in safari  browser ?

**Comment by ain** [comment]
Yes, it is. Please refer to [Hide the smartbanner for certain User Agents](https://github.com/ain/smartbanner.js#hide-the-smartbanner-for-certain-user-agents).

In your case the following should do:

```html
<meta name="smartbanner:exclude-user-agent-regex" content=".*Safari.*">
```

**Comment by RoySegall** [comment]
but this hides the bar for chrome on iPhone as well. Is there any way to programmatically set the banner as I want to?

**Comment by ain** [comment]
iPhone also runs Safari. In that case you need to work out a regular expression that targets desktop exclusively.

**Comment by RoySegall** [comment]
the thing is - I need to show this on:
chrome - andoird and iphone
safari - not at all.

there is a legacy code in the project that can detect it but I need  that the bar will be disabled by default and I could do something like:
```js
smartbanner = new SmartBanner();
if (foo) {
  smartbanner.publish();
}
```

Is that possible?

**Comment by RoySegall** [comment]
Never mind, I used something like this:
```js
      var md = new MobileDetect(window.navigator.userAgent);

      if (md.userAgent() == 'Safari') {
        $('body').addClass('hide-smartapp-banner');
      }
```

And the css is
```
.hide-smartapp-banner .smartbanner {
  display: none !important;
}
```

Thanks a lot for this awesome plugin.

**Comment by ranihorev** [comment]
Hey,
You can hide the banner only on iOS Safari using the following exclusion:
`<meta name="smartbanner:exclude-user-agent-regex" content="^.*iPhone(?!.*CriOS).*Safari">`

**Comment by DevMo99** [comment]
You can use this exclusion
<meta name="smartbanner:exclude-user-agent-regex"  content="^((?!Chrome|Android|FxiOS|CriOS).)*Safari">
