### ISSUE TITLE
Error: Node modules is not recognized as an internal or external command (Windows Users)

### ISSUE THREAD

**Issue by wandesky** [ain/smartbanner.js#76]
__Steps to reproduce__:

1.When attempting 'npm run build' command in Windows platform
2.
3.

__What happens__: The following error is displayed: 'node modules' is not recognized as an internal or external command

__What should happen__:Rendering should be ongoing
![image](https://user-images.githubusercontent.com/19204205/35565118-5347c984-05cd-11e8-8bb0-ff433668c607.png)

**Comment by ain** [comment]
This is Windows-related problem with glob pattern and probably comes from https://github.com/jonschlinkert/add-banner We need to see how to fix this and if we can send a PR to @jonschlinkert on it.

**Comment by ain** [comment]
@wandesky could you please check out `fix-windows-node-sass-failure` branch and let me know if it resolves your `npm run build` problem?
