### ISSUE TITLE
Smart Banner isn't showing up on Safari 

### ISSUE THREAD

**Issue by MikeIsHereWorking** [ain/smartbanner.js#77]
__Environment__
OS: iOS 9,11
Device: iPhone 6, 10

This is the user agent of the iPhone device where I found the problem

    Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A405 Safari/601.1

__Steps to reproduce__:
Similar to https://github.com/ain/smartbanner.js/issues/66 but I need it to work in Safari 
1. Install smartbanner.js on your web server (in my case it's nginx + PHP-FPM)
2. Add these meta tags to your <head>

    `<meta name="apple-itunes-app" content="app-id={redacted}">`
    `<meta name="apple-mobile-web-app-capable" content="yes">`
    `<meta name="apple-touch-icon" content="/Images/Core/favicons/apple-touch-icon-57x57.png">`
    `<meta name="mobile-web-app-capable" content="yes">`
    `<meta name="google-play-app" content="app-id={redacted}">`
3.  Add JS
	`$(document).ready(function () {`
	`	$.smartbanner({`
	`		title: "TITLE", // What the title of the app should be in the banner (defaults to <title>)`
	`		author: "AUTHOR, // What the author of the app should be in the banner (defaults to <meta name="author"> or hostname)`
	`		price: "FREE", // Price of the app`
	`		appStoreLanguage: "us", // Language code for App Store`
	`		inAppStore: "On the App Store", // Text of price for iOS`
	`		inGooglePlay: "In Google Play", // Text of price for Android        `    
	`		GooglePlayParams: null, // Aditional parameters for the market`
	`		iconGloss: null, // Force gloss effect for iOS even for precomposed`
	`		url: null, // The URL for the button. Keep null if you want the button to link to the app store.`
	`		button: "VIEW", // Text for the install button`
	`		scale: "auto", // Scale based on viewport size (set to 1 to disable)`
	`		speedIn: 300, // Show animation speed of the banner`
	`		speedOut: 400, // Close animation speed of the banner`
	`		daysHidden: 0, // Duration to hide the banner after being closed (0 = always show banner)`
	`		daysReminder: 0, // Duration to hide the banner after "VIEW" is clicked *separate from when the close button is clicked* (0 = always show banner)`
	`		force: null, // Choose 'ios', 'android' or 'windows'. Don't do a browser check, just always show this banner`
	`		hideOnInstall: true, // Hide the banner after "VIEW" is clicked.`
	`		layer: false, // Display as overlay layer or slide down the page`
	`		iOSUniversalApp: true, // If the iOS App is a universal app for both iPad and iPhone, display Smart Banner to iPad users, too.      `
	`		appendToSelector: "body", //Append the banner to a specific selector`
	`		onInstall: function () {`
	`		},`
	`		onClose: function () {`
	`			$('#smartbanner').slideUp('slow');`
	`		}`
	`	});`
	`});`

__What happens__:
![image](https://user-images.githubusercontent.com/14020538/35982164-190820d8-0cbd-11e8-88f6-c64346cbe82a.png)

__What should happen__:
Banner should display overriding the safari default.

**Comment by ain** [comment]
You're mixing several Smart Banner implementations and that is the essential reason for your failure. `smartbanner.js` does not require any JavaScript. Please see [Basic Usage documentation of smartbanner.js](https://github.com/ain/smartbanner.js#basic-usage).

**Comment by MikeIsHereWorking** [comment]
My apologies, apparently we were using https://github.com/jasny/jquery.smartbanner

**Comment by ain** [comment]
@MikeIsHereWorking no probs. Make sure to take a dive into `smartbanner.js` as well. It's trivial to set it up!
