### ISSUE TITLE
Smart Banner not working on Production

### ISSUE THREAD

**Issue by DakshAg62** [ain/smartbanner.js#801]
__Steps to reproduce__:

Do all the steps in readme file 
Structure of the files:
Public :
-index.html
-smartbanner.css
-smartbanner.js

this is my Index.html file code:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"
    />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="%REACT_APP_FAVICON_LINK%"
    />
    <title>%REACT_APP_TITLE%</title>
    <meta name="description" content="%REACT_APP_DESCRIPTION%"/>
    <meta property="og:type"  content="website" />
    <meta name="og:title" content="%REACT_APP_OG_TITLE%"/>
    <meta name="og:description" content="%REACT_APP_OG_DESCRIPTION%"/>
    <meta name="og:image" content="%REACT_APP_OG_IMAGE%"/>

    
    <meta name="smartbanner:title" content="%REACT_APP_SMART_BANNER_TITLE%">
    <meta name="smartbanner:author" content="">
    <meta name="smartbanner:price-suffix-apple" content="%REACT_APP_SMART_BANNER_SUBTITLE%">
    <meta name="smartbanner:price-suffix-google" content="%REACT_APP_SMART_BANNER_SUBTITLE%">
    <meta name="smartbanner:icon-apple" content="%REACT_APP_SMART_BANNER_ICON%">
    <meta name="smartbanner:icon-google" content="%REACT_APP_SMART_BANNER_ICON%">
    <meta name="smartbanner:button-url-apple" content="%REACT_APP_SMART_BANNER_CTA_URL%">
    <meta name="smartbanner:button-url-google" content="%REACT_APP_SMART_BANNER_CTA_URL%">
    <meta name="smartbanner:button" content="%REACT_APP_SMART_BANNER_CTA%">
    <meta name="smartbanner:enabled-platforms" content="android,ios">
    <meta name="smartbanner:close-label" content="Close">
    <meta name="apple-itunes-app" content="app-id=%REACT_APP_APP_STORE_ID%">
    <link rel="stylesheet" href="smartbanner.css">
    <link rel="manifest" href="/manifest.json">
    

    <style>
      body {
        overscroll-behavior: none;
      }
      textarea:focus {
        outline: none;
      }
    </style>
    <script>
      console.tron = {};
      console.tron.log = console.log;
    </script>
    
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '%REACT_APP_WEB_FACEBOOK_PIXEL_ID%');
      fbq('track', 'PageView');
    </script>
    
    <noscript>
      <img height="1" width="1" style="display:none" 
          src="https://www.facebook.com/tr?id=%REACT_APP_WEB_FACEBOOK_PIXEL_ID%&ev=PageView&noscript=1"/>
    </noscript>
    

    
     
    <script src="https://maps.googleapis.com/maps/api/js?key=%REACT_APP_GOOGLE_API_KEY%"></script>
    <script type="text/javascript">!function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script>
    <script>
      function isSafari() {
        return navigator.vendor && navigator.vendor.indexOf('Apple') > -1 &&
               navigator.userAgent &&
               navigator.userAgent.indexOf('CriOS') == -1 &&
               navigator.userAgent.indexOf('FxiOS') == -1;
      }

      if (!isSafari()) {
        // If not Safari, load SmartBanner
        var script = document.createElement('script');
        script.src = "smartbanner.js";
        document.head.appendChild(script);
      }
    </script>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>

__What happens__: The banner works on localhost server but it does not works on production. On production it throws an error 
Unexpected token '<' (at smartbanner.js:1:1). I get html code inside the smartbanner.js file

__What should happen__:

**Comment by ain** [comment]
Since you're using the source and it works on local and not in production, the error seems to come from your bundling.

Instead, please use the ready-made files in dist/ as is and let me know know goes.

**Comment by ain** [comment]
Given the error, the problem clearly relates to React use and how the meta tags are used.

Also, with React, API use of `smartbanner.js` is advised.

On these grounds, considering closed.
