### ISSUE TITLE
Once per session

### ISSUE THREAD

**Issue by MikeIsHereWorking** [ain/smartbanner.js#82]
__Steps to reproduce__:

1. Here is the config 
```
     <meta name="smartbanner:title" content="Company" />
     <meta name="smartbanner:author" content="ME" />
     <meta name="smartbanner:price" content="FREE" />
     <meta name="smartbanner:price-suffix-apple" content=" - On the App Store" />
     <meta name="smartbanner:price-suffix-google" content=" - In Google Play" />
     <meta name="smartbanner:icon-apple" content="/~/media/g" />
     <meta name="smartbanner:icon-google" content="/~/media/p" />
     <meta name="smartbanner:button" content="VIEW" />
     <meta name="smartbanner:button-url-apple" content="https:///itunes.apple.com/us/app/" />
     <meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=" />
     <meta name="smartbanner:enabled-platforms" content="android,ios" />
```

__What happens__:
Everything works fine but on the next session on a physical device (Samsung Galaxy S4 samsung-sgh-i337) Android 4.4.4, the smartbanner does not appear.  
I kill the browser app (chrome 64.0.3282.137), to ensure new session

__What should happen__:
I thought the cookie was defaulted to current session.  So the banner should appear on each visit.

**Comment by ain** [comment]
I believe the closing behaviour is the same as for the native Smart App Banner. 

If you need different behaviour, please see https://github.com/ain/smartbanner.js#time-limited-close
