### ISSUE TITLE
Cannot set property outerHTML of #<HTMLElement> which has only a getter

### ISSUE THREAD

**Issue by pvanzini** [ain/smartbanner.js#83]
__Steps to reproduce__:

1. I setup JS + CSS + meta on my page (JS and CSS contained in dist folder)
2. I display the page where script are inserted
3. Banner is not displayed due to a javascript error

__What happens__:
Error on Chrome: 
uncaught TypeError: Cannot set property outerHTML of #<HTMLElement> which has only a getter
    at SmartBanner.publish (smartbanner.js?v=1519147006:310)
    at smartbanner.js?v=1519147006:121

__What should happen__:
Banner should be displayed
Remark : Using index.html you provided, I got no issue

**Comment by ain** [comment]
Thanks for the report @pvanzini. Could you please provide me with the meta tags you're using?

**Comment by pvanzini** [comment]
Thanks for answer @ain 
`

<meta name="smartbanner:title" content="Smart Application">
--
  | <meta name="smartbanner:author" content="SmartBanner Contributors">
  | <meta name="smartbanner:price" content="FREE">
  | <meta name="smartbanner:price-suffix-apple" content=" - On the App Store">
  | <meta name="smartbanner:price-suffix-google" content=" - In Google Play">
  | <meta name="smartbanner:icon-apple" content="http://a3.mzstatic.com/us/r30/Purple60/v4/c1/3b/b0/c13bb085-64c0-cc90-f97a-521b96963986/icon350x350.jpeg">
  | <meta name="smartbanner:icon-google" content="http://lh3.ggpht.com/f4oX61ljZ6x8aYDELZOgxlvdUEu73-wSQ4fy5bx6fCRISnZP8T353wdaM43RO_DbGg=w300">
  | <meta name="smartbanner:button" content="View">
  | <meta name="smartbanner:button-url-apple" content="https://itunes.apple.com/us/genre/ios/id36?mt=8">
  | <meta name="smartbanner:button-url-google" content="https://play.google.com/store">
  | <meta name="smartbanner:enabled-platforms" content="android,ios">
  | 
  | 
  | 
  | 
  | 
  | 

`

**Comment by ain** [comment]
@pvanzini something went wrong there, please revise.

**Comment by pvanzini** [comment]
@ain done. Sry !

**Comment by wandesky** [comment]
@pvanzini  I have tried to reproduce your error but the code works fine on my PC. Could you please add more details on how to recreate the issue?

**Comment by ain** [comment]
Can not be reproduced, closing. 

`smartbanner` should be used with just `meta` tags, no API is currently exposed.
