### ISSUE TITLE
Samsung Browser

### ISSUE THREAD

**Issue by MikeIsHereWorking** [ain/smartbanner.js#84]
Background: 
According to issue #3 smartbanner.js works with 

- Android 6 (Samsung Galaxy S7, Nexus 6, Moto X 2nd gen)
- Android 5 (Samsung Galaxy S6)
- Android 4.4 (Samsung Galaxy S5)

However, I can not get smartbanner to appear on a Galaxy S5, 6, 7  It does work in S8 and S8+ (Andriod 7)
It does work in Chrome and Firefox for all devices

__Steps to reproduce__:

1. Here is the config 
```
     <meta name="smartbanner:title" content="Company" />
     <meta name="smartbanner:author" content="ME" />
     <meta name="smartbanner:price" content="FREE" />
     <meta name="smartbanner:price-suffix-apple" content=" - On the App Store" />
     <meta name="smartbanner:price-suffix-google" content=" - In Google Play" />
     <meta name="smartbanner:icon-apple" content="/~/media/g" />
     <meta name="smartbanner:icon-google" content="/~/media/p" />
     <meta name="smartbanner:button" content="VIEW" />
     <meta name="smartbanner:button-url-apple" content="https:///itunes.apple.com/us/app/" />
     <meta name="smartbanner:button-url-google" content="https://play.google.com/store/apps/details?id=" />
     <meta name="smartbanner:enabled-platforms" content="android,ios" />
```

I use browser stack for testing 

__What happens__:
Nothing, no errors, no banner

__What should happen__:
Banner should appear

**Comment by ain** [comment]
I can confirm supporting the following platforms with Samsung browsers:

- `- Mozilla/5.0 (Linux; Android 7.1.1; SAMSUNG SM-N950F/N950FXXU1AQH9 Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36`
-  `Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G950F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36`
- `Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-G955F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36`
- `Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G930F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36`
- `Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-G920F Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36`

Platforms known to fail:

- `Mozilla/5.0 (Linux; Android 4.4.2; en-us; SAMSUNG SM-G900H Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.6 Chrome/28.0.1500.94 Mobile Safari/537.36` (Samsung browser using Chrome 28)

As @MikeIsHereWorking mentioned, Chrome and Firefox have been tested working down to 4.4.

**Comment by ain** [comment]
Having researched the topic, ancient Samsung browsers were launched at such quality and lack of features, that supporting this sort of backwards compatibility is not reasonable nor easily doable without having impact on the modern platforms.

If you really need it though, feel free to send PR.
