### ISSUE TITLE
optionparser uses weird approach that is not working in all browsers (IE11)

### ISSUE THREAD

**Issue by indreka** [ain/smartbanner.js#89]
IE11 errors out when smartbanner is run, Array.from and Array.includes are missing. And polyfills for both of them are pretty big.

After checking the code:
          if (Array.from(optionName).includes('-'))

This line converts string to char array (using function not supported in IE11) and checks if the char array contains char '-' (using another function not supported in IE11).

Equivalent code without any polyfill-needing functions:
          if (optionName.indexOf('-') != -1) {

Another line:
Array.from(metas).forEach(function (meta) {

Again, Array.from does not work in IE11, simpler alternative would be:
for (let i = 0; i < metas.length; i++) {
  let meta = metas[i];

**Comment by ain** [comment]
As by the documentation, Windows Phone and IE 11 is not supported. 

Polyfills were just recently removed to lose weight on modern platforms.

**Comment by indreka** [comment]
Removing of polyfills was not the point, point was about inefficiencies:
Array.from(optionName).includes('-')
That line explodes a string into characters and then searches the array, which is exactly equivalent to optionName.indexOf('-') != -1
The main difference is that the latter (indexOf version) does not create unneeded char array.
