### ISSUE TITLE
Smart banner is slow to show up

### ISSUE THREAD

**Issue by zusanisha** [ain/smartbanner.js#98]
__Steps to reproduce__:

1.open up the webpage where the smart banner is supposed to show up

__What happens__:

Seconds after the webpage is fully loaded, the smart banner finally starts to show up, or not show up at all.

Sometimes, I need to refresh the webpage a couple of times in order to see the smart banner.

__What should happen__:

The smart banner should show up immediately along with the webpage.

**Comment by ain** [comment]
Current smartbanner strategy is such that it creates the banner in last order, after everything else has been loaded, as per [window.onload](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload). This is to make sure all banner styles are there as well as not to appear invasive.

We may consider other strategies in future versions (>2).
